let name='oyon';
//console.log(name);
let score=20;
let bonus=100;
//console.log(score+bonus);
let firstName='oyon';
let lastName='chattorjee';
//console.log(firstName+' '+lastName);
let tempInFarenheit=100;
let celcius = (tempInFarenheit-32)*(5/9);
console.log(celcius);
